language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: olGA6itSlxu/lDV76me06Ww7Ap9KmeG/SqMsG70fd/MSadUZOWj6fhNBVCwZsDXt8w2LKF0Q/OtiZMQ2yxP/efgnM+NeVTJ/2Zf/hPaP0MuOuFkCimhkkikNqK+WgzgMEoklR9BHOswO/o/a9KR2PHUbtb2MxGxlPs5jFPfh5+XbHhiSD0hd7S2PaPmjG5Wvb3xZFd1gCntYY08zy1vgzpuDG3X9Kw4hjIDojchOWwQh5tFq7QpjLZCRg7gYkh4yUkgb3oqglSoD4OqEb5fYUknGkxQRcqy9n5H2cUt3jSy+GCrngnU9+fQCzF/pXI3+a0eX176G0XpHHyTZ7aWoYGqZuPHYt+tBz7mBWeuICtFvR1poGuBr7hH7hZIfXkrNGwUPxXsWo0b2ZaoNP7igqEWxwHMFElAKHrg2TiNqCvmOz/B4JqXQ9FC0JtEu18Goi7SNNDVRubqNvOKu9ZIVCaUccYTSmEAiwt/RKrTVi3MUKx0ZPjHsOzJHQc+MsqiuzrI1t3qRZSgNE+gHrWUsr7HiNMCWaDohGoLmqNyaaGmCa9ThqgRRAP1vh9dJJ3EeZdg24ika12PAfvkQAiMXJpP/yqOSwB3Beq3anqODdPkKx+F4TnYMLBPP9ZCzlzLnHpRnxgFIuYIsPdIpqx8cCBJ/dQKpCnPyBJ4WsKJwq4s=
  app: frozen-scrubland-29284
  on:
    repo: raysmithdev/guestbook-api
